[build]
  command = "pnpm generate"
  publish = "dist"

[functions]
  directory = "netlify/functions"
[identity]
  provider = "netlify"


[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
